[package]
name = "bve-conveyor"
version = "0.1.0"
description = "Buffer belt abstraction for wgpu"
license = "MPL-2.0"
authors = ["Connor Fitzgerald <connorwadefitzgerald@gmail.com>"]
edition = "2018"

[dependencies]
async-std = "1.6"
bitflags = "1"
lru = { version = "0.5", default-features = false }
wgpu = { git = "https://github.com/gfx-rs/wgpu-rs.git", rev = "90307b6715f5c591db3dc7a067b704a501756557" }

